import { IPlayers } from "@/intefaces/IGame";

export const testData: Array<IPlayers> = [
  {
    name: "Test",
    room: "TYN2",
    avatar: "/src/assets/avatars/6.svg",
    userId: "sffaV2wF1m_mGy30AAAD",
    count: 200,
    oldCount: 100,
    curse: [],
    isReady: true,
    winningQuote: "123123",
    stats: {
      health: 1,
      power: 1,
      magic: 4,
      intelligence: 5,
      luck: 4,
    },
    spellList: [
      {
        name: "coldCharm",
        label: "Криострасть",
        quantity: 2,
      },
      {
        name: "secretException",
        label: "Секретел",
        quantity: 2,
      },
      {
        name: "silenceWisdom",
        label: "Интерруптус",
        quantity: 1,
      },
      {
        name: "secretRiddle",
        label: "Секретная загадка",
        quantity: 2,
      },
    ],
  },
  {
    name: "Rinat",
    room: "TYN2",
    avatar: "/src/assets/avatars/15.svg",
    isReady: true,
    userId: "yafQqKtFKwHJSPYTAAAB",
    count: 400,
    oldCount: 500,
    isRoomAdmin: true,
    curse: [],
    winningQuote: "123",
    stats: {
      health: 1,
      power: 2,
      magic: 3,
      intelligence: 5,
      luck: 4,
    },
    spellList: [
      {
        name: "coldCharm",
        label: "Криострасть",
        quantity: 2,
      },
      {
        name: "secretException",
        label: "Секретел",
        quantity: 1,
      },
      {
        name: "silenceWisdom",
        label: "Интерруптус",
        quantity: 2,
      },
    ],
  },
  {
    name: "Evelina",
    room: "TYN2",
    avatar: "/src/assets/avatars/15.svg",
    isReady: true,
    userId: "yafQqKtFKwHJSPYTAAABzxczxczczxczcx",
    count: 500,
    oldCount: 400,
    isRoomAdmin: true,
    curse: [],
    winningQuote: "123",
    stats: {
      health: 1,
      power: 2,
      magic: 3,
      intelligence: 5,
      luck: 4,
    },
    spellList: [
      {
        name: "coldCharm",
        label: "Криострасть",
        quantity: 2,
      },
      {
        name: "secretException",
        label: "Секретел",
        quantity: 1,
      },
      {
        name: "silenceWisdom",
        label: "Интерруптус",
        quantity: 2,
      },
    ],
  },
  {
    name: "Azat",
    room: "TYN2",
    avatar: "/src/assets/avatars/15.svg",
    isReady: true,
    userId: "yafQqKtFKwHJSPYTAAABasdasdasd",
    count: 50,
    oldCount: 150,
    isRoomAdmin: true,
    curse: [],
    winningQuote: "123",
    stats: {
      health: 1,
      power: 2,
      magic: 3,
      intelligence: 5,
      luck: 4,
    },
    spellList: [
      {
        name: "coldCharm",
        label: "Криострасть",
        quantity: 2,
      },
      {
        name: "secretException",
        label: "Секретел",
        quantity: 1,
      },
      {
        name: "silenceWisdom",
        label: "Интерруптус",
        quantity: 2,
      },
    ],
  },
  {
    name: "Ruzel",
    room: "TYN2",
    avatar: "/src/assets/avatars/15.svg",
    isReady: true,
    userId: "yafQqKtFKwHJSPYTAAAB123123123",
    count: -100,
    oldCount: 0,
    isRoomAdmin: true,
    curse: [],
    winningQuote: "123",
    stats: {
      health: 1,
      power: 2,
      magic: 3,
      intelligence: 5,
      luck: 4,
    },
    spellList: [
      {
        name: "coldCharm",
        label: "Криострасть",
        quantity: 2,
      },
      {
        name: "secretException",
        label: "Секретел",
        quantity: 1,
      },
      {
        name: "silenceWisdom",
        label: "Интерруптус",
        quantity: 2,
      },
    ],
  },
];
